CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS public.projects(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(250) NOT NULL,
    description VARCHAR(250) NOT NULL,
    url VARCHAR(250) NOT NULL,
    cover VARCHAR(250) NOT NULL
)
"""